charts/spark-operator-static/Chart.yaml, charts/spark-operator-static/templates/spark-driver-rbac.yaml
While Spark is shutting down (after a kill), the driver was logging the following:
```
21/11/10 12:47:30 ERROR Utils: Uncaught exception in thread shutdown-hook-0
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/spark-apps/services?labelSelector=spark-app-selector%3Dspark-56a9998472f54cfd9a36bbfccbdaacf8. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services is forbidden: User "system:serviceaccount:spark-apps:spark-driver" cannot list resource "services" in API group "" in the namespace "spark-apps".
```
```
21/11/10 12:47:30 ERROR Utils: Uncaught exception in thread shutdown-hook-0
io.fabric8.kubernetes.client.KubernetesClientException: Failure …
```
=> spark-operator-static 0.1.2

charts/bigdata-notebook-service-storage-server/Chart.yaml, charts/bigdata-notebook-service-storage-server/templates/notebook-service-storage-deployment.yaml, charts/bigdata-notebook-service-storage-server/values.yaml, charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/templates/deployment.yaml, charts/bigdata-notebook-service/values.yaml
The bigdata-notebook-service and bigdata-notebook-service-storage-server should be run on OD instances, and not be scaled down during bin-packing operations
=> bigdata-notebook-service on-demand and restrict scale down

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/role.yaml, charts/bigdata-spark-watcher/values.yaml
- bump to v0.1.3
- add permission to delete sparkapps - required for hammer kill
- require OD (will be required for our system components)
=> bigdata-spark-watcher v0.1.3

charts/spark-operator/Chart.yaml, charts/spark-operator/charts/spark-operator/templates/rbac.yaml, charts/spark-operator/charts/spark-operator/templates/webhook-cleanup-job.yaml, charts/spark-operator/charts/spark-operator/templates/webhook-init-job.yaml, charts/spark-operator/charts/spark-operator/values.yaml, charts/spark-operator/values.yaml
Helm hook fixes. See comments.
=> spark-operator v0.1.4

charts/bigdata-notebook-service-storage-server/Chart.yaml, charts/bigdata-notebook-service-storage-server/values.yaml, charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml, charts/spark-operator/Chart.yaml, charts/spark-operator/values.yaml
Increase requests.
This will put us at 3 vCPU requested, and 3500 MiB, total.
With the increases for spark-operator, bigdata-spark-watcher, bigdata-proxy, we were already above 2 vCPU (`$family.large`), so I also increased bigdata-operator and bigdata-notebook-service-storage-server.
=> Bump requests

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/role.yaml, charts/bigdata-spark-watcher/templates/role_binding.yaml, charts/bigdata-spark-watcher/values.yaml
* bump resources - previous resources were not enough in a high volume cluster
* reduce kill and ghost grace periods, they were unnecessarily high (the k8s commands have a 5 min timeout)
* bump to version 0.2.2 (kill sync reworked, creds refresh)
* adds pod delete permission in spark-apps namespace, which was missing
=> bigdata-spark-watcher 0.2.5

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/values.yaml
- turn off idle kernel culling, we use the timeout feature instead
=> bigdata-notebook-service 0.1.20

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/role.yaml, charts/bigdata-spark-watcher/values.yaml
- clear executor statuses if request is too large error (executor storms)
=> bigdata-spark-watcher v0.2.12

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/templates/deployment.yaml, charts/bigdata-notebook-service/templates/role.yaml, charts/bigdata-notebook-service/templates/role_binding.yaml, charts/bigdata-notebook-service/values.yaml, charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/templates/role.yaml, charts/bigdata-operator/templates/role_binding.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/templates/deployment.yaml, charts/bigdata-proxy/templates/role.yaml, charts/bigdata-proxy/templates/rolebinding.yaml, charts/bigdata-proxy/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/role.yaml, charts/bigdata-spark-watcher/templates/role_binding.yaml, charts/bigdata-spark-watcher/values.yaml, charts/spark-operator/Chart.yaml, charts/spark-operator/values.yaml
Update images with support for multiple spark app namespaces, and expand roles to allow app runs in more namespaces
- bigdata-notebook-service 0.1.21
- bigdata-operator 0.1.30
- bigdata-proxy 0.2.9
- bigdata-spark-watcher 0.2.13
- spark-operator 0.1.18
=> [BGD-2938] Spark app namespaces

charts/bigdata-notebook-service-storage-server/Chart.yaml, charts/bigdata-notebook-service-storage-server/values.yaml, charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/values.yaml, charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml, charts/spark-operator/Chart.yaml, charts/spark-operator/values.yaml
Azure adds a taint to all Spot nodes.
See: https://learn.microsoft.com/en-us/azure/aks/spot-node-pool#verify-the-spot-node-pool
We add a toleration for this taint to our system pods. We want to choose if they run on OD or spot using the `spotinst.io/node-lifecycle: od/spot` pod affinities - so it works the same on all cloud providers.
=> add tolerations for kubernetes.azure.com/scalesetpriority taints

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml
* bigdata-operator 0.1.34
* Use annotation operator.bigdata.spot.io/operatorNamespace
* Support Ocean controller in arbitrary namespace
* bigdata-spark-watcher 0.2.16
* Support Ocean controller in arbitrary namespace
=> Support Ocean controller in arbitrary namespace

charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/templates/role.yaml
We need to add an extra privilege to the bigdata proxy to be able to delete pods
=> Adding delete pod rights to proxy resource monitor role

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml
bigdata-spark-watcher version bump, handling executor storms after application has started running
[BGD-3700](https://spotinst.atlassian.net/browse/BGD-3700)
[BGD-3700]: https://spotinst.atlassian.net/browse/BGD-3700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> version bump

charts/bigdata-crds/.helmignore, charts/bigdata-crds/Chart.yaml, charts/bigdata-crds/templates/bigdata.spot.io_bigdatacomponents.yaml
In order to manage custom resources out of band from the default helm crd installation process a new helm chart has been introduced that enables us to deploy crds just like normal resources. This has the advantage that we can actually introduce a new resource through upgrades since helm only installs crds at install time.
=> BGD-3880 - Helm chart to manage bigdata custom resrouces added

charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/templates/ingress.yaml, charts/bigdata-proxy/values.yaml
The bigdata proxy is now proxying requests into the notebook service, this means that calls to the session creation can take a long time.
We will need to increase the `nginx` → `upstream` timeout
https://spotinst.atlassian.net/browse/BGD-4148
=> Ingress Proxy read timeout set to 600 seconds

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml
Bigdata operator release version 0.4.3
[BGD-4307](https://spotinst.atlassian.net/browse/BGD-4307)
[BGD-4307]: https://spotinst.atlassian.net/browse/BGD-4307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bigdata-operator_0.4.3 release

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-workspace/Chart.yaml, charts/bigdata-notebook-workspace/values.yaml
Add EG_LIST_KERNELS true for jlab4 compatibility
[BGD-4393](https://spotinst.atlassian.net/browse/BGD-4393)
[BGD-4393]: https://spotinst.atlassian.net/browse/BGD-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bgd 4393 upgrade workflow notebook image to jupyterlab 4

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml, charts/bigdata-telemetry/Chart.yaml, charts/bigdata-telemetry/templates/thanos-receiver-statefulset.yaml, charts/bigdata-telemetry/values.yaml, charts/spark-operator/Chart.yaml, charts/spark-operator/values.yaml
_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._
_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_
=> [BGD-4448] run DP components as as non root

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml
- Release version 0.4.7 of the operator with better support of the telemetry component.
- Enable the filter to collect only ocean spark components logs when telemetry is enabled. 
- Configure the telemetry sidecar to send logs to ocean spark regional bucket every 5 minutes instead of 15.
https://spotinst.atlassian.net/browse/BGD-4710
=> [charts/bigdata-operator] release version 0.4.7 of bigdata-operator

.github/CODEOWNERS
To minimize the possibility of pushing bugs to customers, PRs for big data charts should only be approved by the team lead.
https://spotinst.atlassian.net/browse/BGD-4803
=> [.github] allow only team-leads to approve PRs

charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/templates/ingress.yaml, charts/bigdata-proxy/values.yaml
https://spotinst.atlassian.net/browse/BGD-4953
This is recording of a 7.4MB file upload to my workspace.
workspace is running on my cluster `manu-dev-3` on which I patch the bigdata-proxy ingress conf adding: 
```
nginx.ingress.kubernetes.io/proxy-body-size: 2M
```
https://github.com/spotinst/bigdata-charts/assets/21658174/d682fd2e-7bde-4ca9-9175-97424a547911
Ingress conf :
CP ingress was running with charts from this PR : spotinst/bigdata-internal-charts#392
When uploading files from JupyterLab, the chunks sometimes are bigger than the expected 1MB.
Nginx returns `a 413 Payload too large` in those cases
This increase the limit to 2MB, it should be enough. Same change will be done in CP ingress
=> [BGD-4953] increase nginx body size limit

charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/values.yaml
https://spotinst.atlassian.net/browse/BGD-4990
Required to enable large file save on workspaces:
Workspace don't save notebook content using chunks like it does for upload, so we need to bump nginx body-size limit to let the request pass and avoid a `413 Payload too large` error
I find 15M to be a fair size for the usage. On ancient jupyter notebook version it was the limit for file upload.
bump `bodySize` to `15M`
~~Do I need to bump the chart version as well~~ -> Yes
Worked with body-size bumped as well on Control plane with this : spotinst/bigdata-internal-charts#399
Cluster ingress-nginx conf : 
Recording
https://github.com/spotinst/bigdata-charts/assets/21658174/c7a841d5-4985-4397-a50b-e6fff82635ae
=> [BGD-4990] bump proxy-body-size to 15M to fix workspace

charts/bigdata-telemetry/Chart.yaml, charts/bigdata-telemetry/templates/thanos-receiver-service.yaml, charts/spark-operator/Chart.yaml, charts/spark-operator/charts/spark-operator/templates/deployment.yaml, charts/spark-operator/charts/spark-operator/templates/telemetry_configmap.yaml
Follows https://github.com/spotinst/bigdata-charts/pull/190: 
- And fixes an indentation issue in the telemetry section in the spark operator deployment
- Fix the port number of the telemetry input config.
- Add a telemetry service with a fixed name to use in the telemetry output plugins.
https://spotinst.atlassian.net/browse/BGD-4866
- `helm upgrade spark-operator-bdenv-v74 charts/spark-operator -n spot-system --debug --set telemetry.enabled=true`
=> [charts/spark-operator] fix indentation in the telemetry sidecar section

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/templates/deployment.yaml
Follows : https://github.com/spotinst/bigdata-charts/pull/196 and https://github.com/spotinst/bigdata-charts/pull/190 
https://spotinst.atlassian.net/browse/BGD-4866 
- Can be tested in a DP cluster with: `helm upgrade bigdata-notebook-service-bdenv-v73 charts/bigdata-notebook-service -n spot-system --debug --set telemetry.enabled=true`
=> [charts/bigdata-notebook-service] Fix volumes in notebook-service when telemtry is enabled

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/templates/deployment.yaml, charts/bigdata-notebook-service/values.yaml, charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/templates/api-service.yaml, charts/bigdata-operator/templates/deployment.yaml, charts/bigdata-operator/templates/metric-service.yaml, charts/bigdata-operator/values.yaml
Remove the need for NFS in the notebook-service
- Add a new API in bigdata-operator for remoteKernelSession
- Make the notebook-service use webhookKernelSessionManager w/ the bigdata-operator
```
2024-04-19T14:33:06Z    INFO    setup    bigdata-operator    {"buildVersion": "0.4.11-429c6a8f", "buildDate": "2024-04-19T13:34:26Z"}
2024-04-19T14:33:06Z    INFO    controller-runtime.metrics    Metrics server is starting to listen    {"addr": ":8080"}
2024-04-19T14:33:06Z    INFO    spotConfigProvider    Found Ocean controller namespace "kube-system"
2024-04-19T14:33:06Z    INFO    setup    oceanControllerNamespace: "kube-system"
2024-04-19T14:33:06Z    INFO    spotConfigProvider    SPOTINST_CLUSTER_IDENTIFIER found in config map kube-system/spotinst-kubernetes-cluster-controller-config …
```
=> use new bigdata-operator as notebook session backend

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/role.yaml
update `bigdata-spark-watcher` cluster role, add permissions for `ocean-controller-ocean-kubernetes-controller` CM and secret
=> BGD-5143 - fix `bigdata-spark-watcher` cluster role

charts/bigdata-notebook-service-static/Chart.yaml, charts/bigdata-notebook-service-static/values.yaml, charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/values.yaml
Because of performance problems we had to reduce the max number of ports available
_Include a link to your Jira Ticket_
_Example: [BGD-5031](https://spotinst.atlassian.net/browse/BGD-5031)_
A demo could be done by running a hight amount test notebooks
[BGD-5031]: https://spotinst.atlassian.net/browse/BGD-5031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> max port moved down to 50100

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml
[BGD-5023](https://spotinst.atlassian.net/browse/BGD-5023)
Release a new bigdata-operator version that fixes the deprecated Kubernetes APIs when upgrading components
https://github.com/spotinst/bigdata-operator/pull/266
- upgrade bigdata-charts to the new version
- the component is up and running
- follow the test plan from the related bigdata-operator PR mentioned above
[BGD-5023]: https://spotinst.atlassian.net/browse/BGD-5023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BGD-5023 - bigdata-operator 0.4.17

charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/values.yaml
[BGD-5118](https://spotinst.atlassian.net/browse/BGD-5118)
Release a new bigdata-proxy version that fixes vulnerabilities discovered in bigdata-proxy
https://github.com/spotinst/bigdata-proxy/pull/61
Review the following properties
In the bigdata-charts/charts/chart.yaml
appVersion: 0.5.4
In the bigdata-charts/charts/values.yaml
image tag: tag: 0.5.4-4546714a
Run helm upgrade:
helm upgrade bigdata-proxy-bdenv-v67 bigdata-proxy --debug -n spot-system
or directly edit the deployment:
k edit deployment bigdata-proxy-bdenv-v67 -n spot-system
image: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-proxy:0.5.3-3862d889
to
image: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-proxy:0.5.4-4546714a
NOTE: when using helm the operator may quickly move it back to the old …
=> BGD-5118 Bigdata Proxy version 0.4.11

charts/bigdata-notebook-service-storage-server/Chart.yaml, charts/bigdata-notebook-service-storage-server/templates/notebook-service-storage-deployment.yaml, charts/bigdata-notebook-service-storage-server/values.yaml, charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/templates/deployment.yaml, charts/bigdata-notebook-service/values.yaml, charts/bigdata-notebook-workspace/Chart.yaml, charts/bigdata-notebook-workspace/templates/deployment.yaml, charts/bigdata-notebook-workspace/values.yaml, charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/templates/deployment.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-proxy/Chart.yaml, charts/bigdata-proxy/templates/deployment.yaml, charts/bigdata-proxy/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/deployment.yaml, charts/bigdata-spark-watcher/values.yaml, charts/spark-operator/Chart.yaml, charts/spark-operator/charts/spark-operator/templates/deployment.yaml, charts/spark-operator/values.yaml
- Use non root container images for telemetry fluent-bit sidecars.
- Use the version fluent-bit 3.0.5 [bitnami non-root images](https://hub.docker.com/layers/bitnami/fluent-bit/3.0.5/images/sha256-f177e1489be0d2c17be2c696e220df118ce0de4e7394f6ad08a935763ba59955?context=explore
) 
⚠️ Needs this PR to be merged and released first https://github.com/spotinst/bigdata-infrastructure/pull/479
https://spotinst.atlassian.net/browse/BGD-5200
After applying the charts (see tests bellow), all components are running with the sidecars as non-root
`kubectl get pods -o jsonpath="{range .items[*]}{'\n'}{.metadata.name}:{range .status.containerStatuses[*]}{'\n\t'}{.name}{'\t'}{.image}{'\t'}{.state}{end}{end}" -n spot-system`
Before applying the charts bellow, set the the telemetry to true
```
telemetry: …
```
=> Bgd 5200 non root fluentbit sidecars

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml
[BGD-5256](https://spotinst.atlassian.net/browse/BGD-5256)
Release of the bigdata operator, which contains notebook service update to use new config endpoints.
Related bigdata-operator PR https://github.com/spotinst/bigdata-operator/pull/281
- helm upgrade from the local chart
```
helm upgrade bigdata-operator bigdata-operator -n spot-system --debug
```
- the bigdata-opearator is up and running with the new image tag
[BGD-5256]: https://spotinst.atlassian.net/browse/BGD-5256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BGD-5256: operator update 0.4.16 - notebook service 0.4.0

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/templates/deployment.yaml, charts/bigdata-operator/values.yaml, charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml
App version of _bigdata-operator_ bumped to the version that has `CLUSTER_INFO_MAX_AGE` support which allows controlling CM regen frequency. Default value is now 2m which guarantees it gets regenerated each time it is called (call frequency is 3-3.5m)
App version of _bigdata-spark-watcher_ bumped to version that removes some caching of values that no longer need to be cached so that we may properly refresh the cached config values on the fly. Cached credentials are now invalidated every 2m.
This allows for smooth migration to the new ocean controller (v2) and no longer requires you to restart any of the spark services. All you will need to do is install the new controller and scale down the old one.
[BGD-5298](https://spotinst.atlassian.net/browse/BGD-5298)
[BGD-5298]: …
=> BGD-5298 ocean controller v2 migration

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml
https://spotinst.atlassian.net/browse/BGD-5448
- apply the chart
- see the spark-watcher is running
- the k8sEventLogCollectorEnabled is enabled
- check logs
```
{"level":"debug","component":"event_logger","timestamp":"2024-07-10T15:20:33Z","message":"New kubernetes event [kind: SparkApplication, namespace: spark-apps, name: alex-ofas-kill-test-d6323-stake, reason: SparkDriverCompleted, message: Driver alex-ofas-kill-test-d6323-stake-driver completed, timestamp: 2024-07-10 15:20:33 +0000 UTC]"}
{"level":"debug","component":"event_logger","timestamp":"2024-07-10T15:20:33Z","message":"New kubernetes event [kind: SparkApplication, …
```
=> BGD-5448 - enable the `k8sEventLogCollectorEnabled` by default

.github/workflows/branch-protection-changes.yaml
Get Alerted when the branch protection rules change
https://spotinst.atlassian.net/browse/BGD-5788
✅ Not a code change and not affecting the current workflows thus all the checks bellow are not applicable
=>  [.github/workflows] add a new workflow to alert on branch protection changes

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/Readme.md, charts/bigdata-notebook-service/templates/role.yaml, charts/bigdata-notebook-service/templates/role_binding.yaml
https://spotinst.atlassian.net/browse/BGD-5797
We want the notebook-service to be able to watch sparkapp CR and add annotations `bigdata.spot.io/kill-requested-at` in them and let spark-watcher kill the app.
This will happen at each kernel shutdown handled by bns
- Apply chart on a cluster with `helm upgrade bigdata-notebook-service-bdenv-vXX bigdata-notebook-service -n spot-system`
- Update your bigdata-notebook-service deployment with the image from this PR  spotinst/bigdata-python-services#1332
- Start a notebook and wait for it to be running
- Click on the restart button in JupyterLab UI
- Check notebook-service manage to update the annotation, you should see something like: 
```
Found CRD for this kernel_id=8221eeb6-2b57-42ea-b51f-9cefea265c1f in namespace=spark-apps
Updated …
```
=> [BGD-5797] add bns role to list and patch CR

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/values.yaml
https://spotinst.atlassian.net/browse/BGD-5896
bigdata-notebook-service nows sets annotation `kill-requested-at` on SparkApp CR when kernel shutdown (or restart) is requested. 
a ClusterRole has been added to allow this behaviour in a previous change.
_Please add a recording/screenshot of the feature/bug fix in action_
- deploy chart `helm upgrade bigdata-notebook-service-bdenv-v30 bigdata-notebook-service -n spot-system`
- run notebooks
- kill and restart them
- check CR contains `kill-requested-at` annotation
| 1    | Chart deployment | Pass   |  |
| 2    | Annotation on killed notebook | Pass   |  |
| 3    | Annotation on restarted notebook | Pass   |  |
=> [BGD-5896] bns set annotation when shutting down a kernel

charts/bigdata-notebook-workspace/Chart.yaml, charts/bigdata-notebook-workspace/values.yaml
https://spotinst.atlassian.net/browse/BGD-5953
The new jupyterlab image contains fixes for switching kernels
Switch kernels should work now
Generate the image using the github actions in bigdata-infrastructure. Ran a workspace on dev and replaced the deployment image tag with the branch name or built by the ci: public.ecr.aws/n8e8v3t5/bigdata-notebook:lab-4.1.8-ofas-31799c9. Launching a new notebook is working and switching kernels is working
=> Bgd 5953 workspace switching kernel causes an error

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/values.yaml
https://spotinst.atlassian.net/browse/BGD-6060
Update spark-watcher to 0.6.1. Before sending the final heartbeat to an application, make sure that the event cache is flushed to persistent storage.
The apps have the following IDs:
```
│ Labels:           bigdata.spot.io/application-id=andrei-beefed-pi-24dfa-hangs
bigdata.spot.io/application-internal-id=53f827b4-8426-44f2-a2f6-2caf3d4ae617                                                                          
│ Labels:           bigdata.spot.io/application-id=andrei-beefed-pi-29e7a-facts
bigdata.spot.io/application-internal-id=e474666f-52f9-446a-ab86-fdcbf96b016a
```
To test this change, we need a DP cluster. Run a very fast application. Logs should be available in the archive bucket (and available to be downloaded if the feature is …
=> BGD-6060 Flush events chunks before final heartbeat

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-6060
Update operator chart as a result of embedded spark-watcher chart update. (spark-watcher 0.6.1)
Upgrade helm release for bigdata-operator. Check the new operator starts without issue
1. Upgrade helm release
```
bandrei@bandrei-mac-0 ~/code/bigdata-charts % helm upgrade bigdata-operator charts/bigdata-operator -n spot-system          
Release "bigdata-operator" has been upgraded. Happy Helming!
NAME: bigdata-operator
LAST DEPLOYED: Wed Oct 30 18:50:19 2024
NAMESPACE: spot-system
STATUS: deployed
REVISION: 6
TEST SUITE: None
NOTES:
Installs the Spot BigData Operator
```
Operator chart is updated without issues. New image of `bigdata-operator` is run
---
2. Check basic operator functionality
Delete `spark-watcher` helm release. Check that the …
=> BGD-6060  bigdata operator embedded charts update

charts/bigdata-notebook-workspace/Chart.yaml, charts/bigdata-notebook-workspace/templates/deployment.yaml, charts/bigdata-notebook-workspace/values.yaml
https://spotinst.atlassian.net/browse/BGD-4766
Our workspace jupyterlab image is based on the https://quay.io/repository/jupyter/base-notebook image, which has userid 1000 for user jovyan and groupid 100 for group users.
It is recommended to use the start-notebook.py instead of the shell script to launch the jupyterlab process, see.
```sh
cat start-notebook.sh 
#!/bin/bash
echo "WARNING: Use start-notebook.py instead"
exec /usr/local/bin/start-notebook.py "$@"
```
Opening a terminal in the workspace notebook no longer runs as root. Also new notebook files are successfully saved on the mounted drive and owned by the jovyan user.
Create a workspace. Edit the deployment and replace the runAsUser: 0 and fsGroup: 0 with 1000 and 100 respectively. Remove the --allow-root and replace …
=> Run workspace as non root

charts/bigdata-operator/Chart.yaml, charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-5995
Set the `restrict-scale-down` label to prevent scaling down a node where the component is running
- upgrade the component
```
helm upgrade bigdata-operator bigdata-operator -n spot-system 
```
- see the label `spotinst.io/restrict-scale-down: "true"`
=> Bgd-5995 set restrict scale down label

charts/bigdata-notebook-service/Chart.yaml, charts/bigdata-notebook-service/values.yaml
https://spotinst.atlassian.net/browse/BGD-6043
Notebook service version 0.100.1 with fixes for scala kernel stability
Launch scala kernel in workspaces. Restart the kernel, the previous should complete and new one get started. Restart the notebook-service. The kernel session should stay intact and not launch a new scala kernel
Launch scala kernel in workspaces. Restart the kernel, restart the notebook-service. The kernel session should stay intact
| Test | Description       | Result | Notes                     |
| ---- | ----------------- | ------ | ------------------------- |
| 1    | Scala notebook restart | Pass   | Previous kernel is shut down and a new SparkApplication successfully started |
| 2    | Python notebook restart | Pass   | Previous kernel is shut down and a new …
=> update notebook service

charts/bigdata-notebook-workspace/Chart.yaml, charts/bigdata-notebook-workspace/templates/deployment.yaml, charts/bigdata-notebook-workspace/values.yaml
https://spotinst.atlassian.net/browse/BGD-6183
Do not mount the token as ENV_VAR `JUPYTER_GATEWAY_AUTH_TOKEN` from the secret created by the bigdata-proxy
see `Test plan and results`
Run the chart on demo-0 and start a notebook
Since the secret is not mounted it means that you are using the browser JWT token
```
Name:             wksp-62236-ddc1997e-5d96fd46dc-rd7rp
Namespace:        spot-system
Priority:         0
Service Account:  default
Node:             ip-192-168-121-103.us-west-2.compute.internal/192.168.121.103
Start Time:       Fri, 22 Nov 2024 09:22:22 +0100
Labels:           app.kubernetes.io/instance=wksp-62236-ddc1997e
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=bigdata-notebook-workspace
app.kubernetes.io/version=4.1.8-ofas-31799c9 …
```
=> workspace chart won't mount JWT secret

charts/bigdata-notebook-workspace/Chart.yaml, charts/bigdata-notebook-workspace/templates/pvc.yaml, charts/bigdata-notebook-workspace/values.yaml
https://spotinst.atlassian.net/browse/BGD-6242
Add values config option to be able to specify the storage class of the PVC in the `bigdata-notebook-workspace` chart.
Given a `values.yaml` containing
```yaml
pvc:
storageClassName: pvc-ebs
```
A PVC with the following spec is generated:  
```yaml
spec:
storageClassName: pvc-ebs
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 10Gi
```
Without providing a `values.yaml`:
```yaml
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 10Gi
```
Helm install the chart with a valid value for `pvc.storageClassName` and check that it is successful and the PVC gets created with `spec.storageClassName` set to the provided value. …
=> BGD-6242 Workspace stuck in starting due to missing volume

charts/bigdata-crds/Chart.yaml, charts/bigdata-crds/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/bigdata-crds/crds/sparkoperator.k8s.io_sparkapplications.yaml, charts/bigdata-crds/templates/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/bigdata-crds/templates/sparkoperator.k8s.io_sparkapplications.yaml
https://spotinst.atlassian.net/browse/BGD-6250
https://spotinst.atlassian.net/browse/BGD-6250
_Please add a recording/screenshot of the feature/bug fix in action_
Testing was done on this PR -> https://github.com/spotinst/bigdata-operator/pull/358
Look into https://github.com/spotinst/bigdata-operator/pull/358 to see the helm upgrade diff works
=> Make bigdata-crds manages spark-operator crds

charts/bigdata-spark-watcher/Chart.yaml, charts/bigdata-spark-watcher/templates/deployment.yaml, charts/bigdata-spark-watcher/values.yaml
https://spotinst.atlassian.net/browse/BGD-6179
Introduces the new env vars required to enable the new cleanup mechanisms for orphaned drivers and stuck failed spark app CRs, as well as bumps the image tag to use the new version.
After applying the chart.
Apply the chart but set the image.tag to `BGD-6179-handle-orphaned-driver-pods` and the image.registry to the private registry.
See PR in the watcher for more details.
| 1    | Apply chart on cluster and see that it is configured correctly | ✅   |  |
| 2    | Integration tests  |  ✅   |   |
| 3    | Have stuck failed app CRs and observe that they get removed |  ✅   |   |
=> BGD-6179 Handle orphaned drivers
