- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/templates/service.yaml
* service port 8080 becomes 80
> bigdata-proxy-0.0.2

- charts/bigdata-notebook-service-storage-server/Chart.yaml
- charts/bigdata-notebook-service-storage-server/README.md
- charts/bigdata-notebook-service-storage-server/templates/NOTES.txt
- charts/bigdata-notebook-service-storage-server/templates/_helpers.tpl
- charts/bigdata-notebook-service-storage-server/templates/notebook-service-storage-deployment.yaml
- charts/bigdata-notebook-service-storage-server/templates/notebook-service-storage-service.yaml
- charts/bigdata-notebook-service-storage-server/values.yaml
- charts/bigdata-notebook-service-storage/Chart.yaml
- charts/bigdata-notebook-service-storage/README.md
- charts/bigdata-notebook-service-storage/templates/NOTES.txt
- charts/bigdata-notebook-service-storage/templates/_helpers.tpl
- charts/bigdata-notebook-service-storage/templates/notebook-service-storage-pv.yaml
- charts/bigdata-notebook-service-storage/templates/notebook-service-storage-pvc.yaml
- charts/bigdata-notebook-service-storage/values.yaml
- bigdata-notebook-service-storage
- bigdata-notebook-service-storage-server
> bigdata-notebook-service-storage

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
* bigdata-operator 0.1.17
* require OD
> bigdata-operator v0.1.17

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
- charts/bigdata-notebook-service/values.yaml
- update image
- roll back account ID from CM - will be added again in a following release
> bns 0.1.10

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
> bns 0.1.11

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
> bigdata-operator 0.1.23

- charts/spark-operator/Chart.yaml
- charts/spark-operator/charts/spark-operator/templates/webhook-cleanup-job.yaml
- charts/spark-operator/charts/spark-operator/templates/webhook-init-job.yaml
- charts/spark-operator/charts/spark-operator/values.yaml
- charts/spark-operator/values.yaml
- require Ocean nodes for webhook job pods
> spark-operator 0.1.7

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
- charts/bigdata-notebook-service/values.yaml
Ensure that the new check-liveness script is called
issue: BGD-2301
Relates to this change: https://github.com/spotinst/bigdata-python-services/pull/483
> Notebook service liveness probe updated

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/values.yaml
[BGD-2318](https://spotinst.atlassian.net/browse/BGD-2318)
> Notebook service updated to 0.1.14

- charts/bigdata-notebook-service-storage-server/Chart.yaml
- charts/bigdata-notebook-service-storage-server/values.yaml
- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/values.yaml
- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/values.yaml
- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
- charts/spark-operator/Chart.yaml
- charts/spark-operator/values.yaml
Add anti-affinities to Spark VNGs, to fall back on in the absence of taints
> [BGD-2320] Node anti-affinities to spark VNGs

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
- charts/bigdata-notebook-service/values.yaml
- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
- spark-watcher 0.2.1
- increase requests and limits on watcher
- set timeout on notebook-service liveness probe
> [BGD-2317][BGD-2429][BGD-2426] Update watcher, bns

- charts/bigdata-notebook-service-storage-server/Chart.yaml
- charts/bigdata-notebook-service-storage-server/values.yaml
cf https://spotinst.atlassian.net/browse/BGD-2434
> [bigdata-notebook-service-storage-server] use volume-nfs image from our public ECR

- charts/spark-operator/Chart.yaml
- charts/spark-operator/charts/spark-operator/templates/deployment.yaml
> spark-operator 0.1.14

- charts/spark-operator/Chart.yaml
- charts/spark-operator/charts/spark-operator/templates/deployment.yaml
- charts/spark-operator/charts/spark-operator/values.yaml
- charts/spark-operator/values.yaml
- new image
- customizations for workqueue
- disable executor reporting flag
> spark-operator 0.1.17

- charts/bigdata-notebook-service-storage-server/Chart.yaml
- charts/bigdata-notebook-service-storage-server/values.yaml
- update volume-nfs image. 
[BGD-2998](https://spotinst.atlassian.net/browse/BGD-2998)
[BGD-2998]: https://spotinst.atlassian.net/browse/BGD-2998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [bigdata-notebook-storage-server] update volume-nfs image

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/deployment.yaml
- charts/bigdata-operator/values.yaml
* Save operator namespace in annotation on BigDataEnvironment
* Remove secret controller
* Inject TLS secret into namespace with label `operator.bigdata.spot.io/injectTLSSecret`
> bigdata-operator 0.1.32

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/values.yaml
Update bigdata-proxy version to 0.2.5
> update bigdata-proxy version

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/templates/clusterrole.yaml
* update role
* new version 0.2.12
> bigdata-proxy restrict rbac

- charts/spark-operator/Chart.yaml
- charts/spark-operator/charts/spark-operator/templates/rbac-namespaced.yaml
- charts/spark-operator/charts/spark-operator/templates/rbac.yaml
* update role, restrict RBAC, move cluster wide privileges to namespaced privileges
* new version 0.1.20
> spark-operator restrict rbac

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
> bigdata-operator 0.2.4

- charts/spark-operator-static/Chart.yaml
- charts/spark-operator-static/templates/spark-driver-rbac.yaml
> spark-operator-static 0.1.5

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/cluster_manager_role.yaml
> bigdata-operator 0.2.5

- charts/spark-operator-static/Chart.yaml
- charts/spark-operator-static/templates/spark-driver-rbac.yaml
- deletecollection permission for config maps
> spark-operator-static 0.1.6

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/cluster_manager_role.yaml
- deletecollection permission for config maps
> bigdata-operator 0.2.6

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
spark-watcher 0.3.2 release
_Include a link to your Jira Ticket_
_Example: [BGD-3574](https://spotinst.atlassian.net/browse/BGD-3574)_
NA
[BGD-3574]: https://spotinst.atlassian.net/browse/BGD-3574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> spark-watcher 0.3.2

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
Use quote for eg response port number
[BGD-3338](https://spotinst.atlassian.net/browse/BGD-3338)
[BGD-3338]: https://spotinst.atlassian.net/browse/BGD-3338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use quote for number

- charts/bigdata-notebook-service-storage-server/Chart.yaml
- charts/bigdata-notebook-service-storage-server/values.yaml
Security patch for the volume-nfs image
https://spotinst.atlassian.net/browse/BGD-3689?atlOrigin=eyJpIjoiYTVhMzEwZjRhZTg3NDlkMGI1MTJjYTAwMGM0NDdlMzMiLCJwIjoiaiJ9
> [charts/bigdata-notebook-storage-server] update volume-nfs image version

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/values.yaml
bigdata-notebook-service new version 0.1.30
[BGD-3736](https://spotinst.atlassian.net/browse/BGD-3736)
[BGD-3736]: https://spotinst.atlassian.net/browse/BGD-3736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  BGD-3736-bigdata-notebook-service 0.1.30

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
bump bigdata-operator version
[BGD-3603](https://spotinst.atlassian.net/browse/BGD-3603)
[BGD-3603]: https://spotinst.atlassian.net/browse/BGD-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bump version

- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/templates/deployment.yaml
Upon looking at the way the start script behaves the container is started as root so that directory privileges can be setup correctly and then the application is started with the Jovyan user
> The application is run as the Jovian user by default and not root

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/templates/clusterrole.yaml
- charts/bigdata-proxy/templates/role.yaml
- charts/bigdata-proxy/values.yaml
Adding rights for bigdata-proxy to manage bigdata components as well as secrets
> BGD-3863 Adding rights to manage secrets and bigdatacomponents

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
bump version for nil pointer fix in executor storm detection
[BGD-3876](https://spotinst.atlassian.net/browse/BGD-3876)
[BGD-3876]: https://spotinst.atlassian.net/browse/BGD-3876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version bump

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/deployment.yaml
- charts/bigdata-operator/values.yaml
- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/templates/deployment.yaml
- charts/bigdata-telemetry/Chart.yaml
- charts/bigdata-telemetry/templates/thanos-receiver-statefulset.yaml
Added HTTP proxy environment variables to all components that have egress traffic.
> BGD-3524 honor proxy configuration in dp components

- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/templates/helpers.tpl
- charts/bigdata-notebook-workspace/values.yaml
https://spotinst.atlassian.net/browse/BGD-3558
> Readded workspace name config parameter

- charts/spark-operator/Chart.yaml
- charts/spark-operator/values.yaml
- new spark-operator version `0.1.22`
- new spark-operator image `1aad721-gen19`
> BGD-4028 spark-operator `0.1.22`

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
Update bigdata-operator image version
[BGD-4166](https://spotinst.atlassian.net/browse/BGD-4166)
[BGD-4166]: https://spotinst.atlassian.net/browse/BGD-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update bigdata-operator image version

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/deployment.yaml
- charts/bigdata-operator/values.yaml
add ocean-controller namespace ENV VAR
> BGD-4221 - ocean-controller namespace ENV VAR

- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/values.yaml
Upgrade to jupyterlab 4
[BGD-4393](https://spotinst.atlassian.net/browse/BGD-4393)
[BGD-4393]: https://spotinst.atlassian.net/browse/BGD-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update to jupyterlab 4

- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/values.yaml
Upgrade to jupyterlab 4.0.10
[BGD-4393](https://spotinst.atlassian.net/browse/BGD-4393)
[BGD-4393]: https://spotinst.atlassian.net/browse/BGD-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BGD-4393-upgrade-to-jlab-4.0.10

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
release the version 0.4.5 of the bigdata-operator
https://spotinst.atlassian.net/browse/BGD-4549?atlOrigin=eyJpIjoiOTBmMTkxYmIwODA5NGM4OTkwZGQ1MGViYmY3NmQ3NTUiLCJwIjoiaiJ9
> release the version 0.4.5 of the bigdata-operator

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/templates/deployment.yaml
- charts/bigdata-spark-watcher/values.yaml
Fix fpassing `enable-ghost-syncer`, `enable-kill-syncer` args
> BGD-4374 Fix passing args

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/templates/deployment.yaml
- charts/bigdata-spark-watcher/values.yaml
- bump chart version
- rename `k8sEventLogCollectorEnabled`
- update image tag
> BGD-4738 - fix bigdata-watcher

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
- fix bigdata-watcher chart values
>  BGD-4741 - fix charts values

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
>  BGD-4743  - bigdata-watcher 0.4.10

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/cluster_manager_role.yaml
https://spotinst.atlassian.net/browse/BGD-4615
To modify leases, we need to grant extra permissions for the `leases` resource.
> BGD-4615 - add `leases` permissions to the `bigdata-operator-cluster-manager` cluster role

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
- bigdata-operator 0.4.10
- Support for embedded charts
> bigdata-operator 0.4.10

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
Upgrade bigdata-spark-watcher
- spark app kube events logger
> BGD-4774 - bigdata-watcher new version

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/cluster_manager_role.yaml
- charts/bigdata-operator/values.yaml
Add permissions to the new ocean-controller components
> BGD-4846 - support new ocean-controller

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/telemetry_configmap.yaml
- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/templates/telemetry_configmap.yaml
- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/templates/common_telemetry_configmap.yaml
- charts/bigdata-operator/templates/deployment.yaml
- charts/bigdata-operator/templates/telemetry_configmap.yaml
- charts/bigdata-operator/values.yaml
- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/templates/telemetry_configmap.yaml
- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/templates/telemetry_configmap.yaml
- charts/bigdata-telemetry/Chart.yaml
- charts/bigdata-telemetry/templates/thanos-receiver-statefulset.yaml
- charts/spark-operator/Chart.yaml
- charts/spark-operator/charts/spark-operator/templates/telemetry_configmap.yaml
- Fix the telemetry charts (refreshing expiring secrets)
- Update the telemetry configmap for all charts to better filter logs.
https://spotinst.atlassian.net/browse/BGD-5066
> Bgd 5066 fix telemetry component

- charts/bigdata-notebook-service-storage-server/Chart.yaml
- charts/bigdata-notebook-service-storage-server/templates/notebook-service-storage-deployment.yaml
- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/templates/deployment.yaml
- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/templates/deployment.yaml
- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/templates/deployment.yaml
- charts/bigdata-telemetry/Chart.yaml
- charts/bigdata-telemetry/templates/thanos-receiver-statefulset.yaml
- charts/spark-operator/Chart.yaml
- charts/spark-operator/charts/spark-operator/templates/deployment.yaml
- Add custom parsers to all sidecars in all the charts
- Set the `failureThreshold` in telemetry component to 2 instead of default 3 to fail fast and restart.
- https://spotinst.atlassian.net/browse/BGD-4867
> Bgd 4867 Add custom telemetry parsers to all components

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/values.yaml
[BGD-4183](https://spotinst.atlassian.net/browse/BGD-4183)
NA
We are pushing a new version of the bigdata-notebook-service. 
This PR is a part of the release process and is accompanied by  this [PR](https://github.com/spotinst/bigdata-charts/pull/200)
[BGD-4183]: https://spotinst.atlassian.net/browse/BGD-4183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update charts for notebook services

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/templates/deployment.yaml
- charts/bigdata-notebook-service/values.yaml
- Quote egListKernels boolean value
- Remove requiredDuringSchedulingIgnoredDuringExecution zone affinity for storage-server
> Bgd 4764 fix bns chart error

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
Update bigdata operator
[BGD-5023](https://spotinst.atlassian.net/browse/BGD-5023)
[BGD-5023]: https://spotinst.atlassian.net/browse/BGD-5023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update bigddata-operator version

- charts/bigdata-notebook-workspace/Chart.yaml
- charts/bigdata-notebook-workspace/templates/deployment.yaml
- charts/bigdata-notebook-workspace/values.yaml
Update notebook to latest version
Updating to latest jupyternotebook version and custom changes for ofas notebooks
[BGD-4926](https://spotinst.atlassian.net/browse/BGD-4926)
[BGD-4926]: https://spotinst.atlassian.net/browse/BGD-4926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update notebook workspaces

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
[BGD-4764](https://spotinst.atlassian.net/browse/BGD-4764)
[BGD-4764]: https://spotinst.atlassian.net/browse/BGD-4764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bigdata-operator v0.4.16

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/values.yaml
[BGD-4667](https://spotinst.atlassian.net/browse/BGD-4667)
_N/A_
[BGD-4667]: https://spotinst.atlassian.net/browse/BGD-4667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BGD-4667] Notebook Service Update - 0.4.0

- charts/spark-operator/Chart.yaml
- charts/spark-operator/values.yaml
Update the spark operator image to patch some vulnerabilities
- [BGD-5482](https://spotinst.atlassian.net/browse/BGD-5482
- Apply the chart to `demo-0` in prod : 
- Chart installed and cluster was green 
[BGD-5482]: https://spotinst.atlassian.net/browse/BGD-5482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BGD-5482 - update spark-operator version

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
[BGD-5122 ](https://spotinst.atlassian.net/browse/BGD-5122 )
- apply the helm chart
- the new version of the component is up and running
- the cluster is available
- run integration tests
- https://github.com/spotinst/bigdata-internal-charts/actions/runs/9941163590
> BGD-5122 - update spark-watcher version

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
[BGD-5122 ](https://spotinst.atlassian.net/browse/BGD-5262 )
- apply the helm chart
- the new version of the component is up and running
- the cluster is available
```
helm upgrade bigdata-spark-watcher-bdenv-v76 bigdata-spark-watcher -n spot-system --debug
```
- run integration tests
- https://github.com/spotinst/bigdata-internal-charts/actions/runs/10131037037
> BGD-5262 - update spark-watcher version

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
[BGD-5552 ](https://spotinst.atlassian.net/browse/BGD-5552 )
- apply the helm chart
- the new version of the component is up and running
- the cluster is available
```
helm upgrade bigdata-operator bigdata-operator -n spot-system --debug
```
> BGD-5552 - update bigdata-operator

- .github/pull_request_template.md
- .github/workflows/lint.yaml
- README.md
https://spotinst.atlassian.net/browse/BGD-5701
- add  I have updated/created relevant documentation to the pull request template
- refresh the README.md
_Please add a recording of the feature/bug fix in work_
> BGD-5701 - update PR template

- .github/pull_request_template.md
- LICENSE
https://spotinst.atlassian.net/browse/BGD-5841
Add Apache 2.0 license
N/A
N/A
N/A
> [BGD-5841] Create LICENSE

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/values.yaml
https://spotinst.atlassian.net/browse/BGD-5674
Version and image tag for bigdata-proxy
> BGD-5674 version 0.5.5 and new image tag

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
https://spotinst.atlassian.net/browse/BGD-5674 
Updated version and tag for new release of spark-watcher
> BGD-5674 app version 0.5.4 and new image tag

- charts/spark-operator/Chart.yaml
- charts/spark-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-5677
Spark operator security patching involving library updates and related code change
With this version of the Spark operator running in the DP
Launch a Spark application via Postman (such as the SparkConnect one)
Launch a new Spark application from a workspace notebook.
Try deleting a running Spark application
Both the Spark application and the Notebook application ran successfully. Spark application deletion works as well
> bump spark-operator chart version

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-5838
- bump bigdata-operator version
- update app version
- update chart version
- update image tag
_Please add a recording/screenshot of the feature/bug fix in action_
- run `helm upgrade bigdata-operator bigdata-operator -n spot-system --debug`
- check that the expected bigdata-operator version is up and running
> BGD-5838 -  - bump bigdata-operator version

- charts/bigdata-spark-watcher/Chart.yaml
- charts/bigdata-spark-watcher/values.yaml
https://spotinst.atlassian.net/browse/BGD-5785
update spark-watcher chart version
- run ` helm upgrade bigdata-spark-watcher-bdenv-vXX bigdata-spark-watcher -n spot-system `
- see the expected version is up and running
> BGD-5785  - update spark-watcher version

- charts/bigdata-notebook-service/Chart.yaml
- charts/bigdata-notebook-service/values.yaml
https://spotinst.atlassian.net/browse/BGD-5081
Fix for case sensitive string compare resulting in failed persistent kernel recovery
See. How to test
Run a notebook in a workspace. Delete/restart the notebook service. See the kernel reconnect instead of getting a new kernel
> update image tag and bump chart version

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-5975
Reconciler updates the component (workspace) status and saves the bigdatacomponent as json blob in db
* run helm upgrade bigdata-operator bigdata-operator -n spot-system
* see the new version is up and running
> update bigdata operator

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-6054
Update `bigdata-operator` chart after `spark-watcher` embedded chart update.
See integration tests below.
Integration tests on prod cluster 
| 1    | Integration tests on prod cluster | Pass   |  |
> BGD-6054 bigdata-operator update for spark-watcher 0.6.3 archive

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-6043
_Description of the work contained in this PR_
See integration tests
Integration tests on prod cluster
_Feel free to add screenshots showing test results_
| 1    | Integration tests on prod cluster | Pass   |   |
> bump notebook service version

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/values.yaml
https://spotinst.atlassian.net/browse/BGD-6184
release new secret workspace management
Demo was done here -> https://github.com/spotinst/bigdata-proxy/pull/69
Test was done on this PR -> https://github.com/spotinst/bigdata-proxy/pull/69
see screenshot from https://github.com/spotinst/bigdata-proxy/pull/69
> release bigdata-proxy 0.5.6 (0.5.6-a233581b)

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-6184
release bigdata-operator 0.5.1 (bigdata-proxy embedded chart)
> release bigdata-operator 0.5.1 (bigdata-proxy embedded chart)

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/values.yaml
https://spotinst.atlassian.net/browse/BGD-6242
Update of bigdata-proxy that supports the new configuration option (storage class name)
N/A
See this PR for more details: https://github.com/spotinst/bigdata-proxy/pull/70
| 1    | Integration tests | ✅ |   |
> BGD-6242 - Workspace stuck in starting due to missing volume - release bigdata-proxy 0.5.7

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-6242
Amongst others. 
This release adds a few embedded charts and some changes to the deployer.
N/A
Apply the chart, everything works.
| 1    | Integration tests | ✅  |  |
> BGD-6242 - Bigdata operator release

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-6196
Update workspaces in bigdatacomponent reconciler
see. https://github.com/spotinst/bigdata-operator/pull/356
see. https://github.com/spotinst/bigdata-operator/pull/356
> update operator chart

- charts/bigdata-proxy/Chart.yaml
- charts/bigdata-proxy/values.yaml
https://spotinst.atlassian.net/browse/BGD-5436
Bumps dependencies in `bigdata-proxy` to resolve vulnerabilities.
N/A
Install chart, run the integration tests
| 1    | Integration tests |  ✅  |   |
> BGD-5436 bigdata-proxy security patch

- charts/bigdata-operator/Chart.yaml
- charts/bigdata-operator/values.yaml
https://spotinst.atlassian.net/browse/BGD-5436
Updates bigdata-operator to include the new embedded chart for bigdata-proxy (0.5.8)
N/A
Apply operator chart, run integration tests.
| 1    | Integration tests |  ✅   |   |
> BGD-5436 bigdata-proxy security patch - update bigdata-operator chart with new embedded chart
